### ISSUE TITLE
text and keyboard input

### ISSUE THREAD

**Issue by ghost** [exiva/Vizio_SmartCast_API#38]
hello

is there a way to send keyboard input and text? so for example instead of using the arrows on the TV, I would just write the text i need using a keyboard and the characters would be sent to the tv.

thanks

**Comment by iOS090Bravo** [comment]
@Ganime422 
Have you configured it yet?

**Comment by exiva** [comment]
Does the app support doing that?

**Comment by kbrown01** [comment]
Yes. You can use ASCII Decimal codes and key_command. For example, this in my setup will (in Home Assistant) take a textbox and send each "letter" as the ord ASCII code:

```
alias: Execute Vizio Search
sequence:
  - repeat:
      sequence:
        - service: rest_command.vizio_processkey
          data:
            ip: 192.168.1.232
            port: "7345"
            auth: XXXXXXXXXX
            codeset: "0"
            code: |
              {{ repeat.item | ord }}
      for_each: |
        {{ states("input_text.vizio_search") | list }}
fields: {}
mode: single
icon: mdi:search-web
```
The command is built like this:

```
vizio_processkey:
  url: 'https://{{ ip }}:{{ port }}/key_command/'
  method: put
  content_type: "application/json"
  headers:
    AUTH: '{{ auth }}'
  payload: '{"KEYLIST": [{"CODESET": {{ codeset | int }},"CODE": {{ code | int }},"ACTION":"KEYPRESS"}]}'
  verify_ssl: false
```
It could be better, like I culd build an array for KEYLIST and send all the keys but it is very fast as is.

So let's say you want to search for "Hot Ones" ... this code in Home Assistant takes that string and converts every letter to it's ASCII equivalent (i.e. "a" = 97) and sends that key stroke. It loops for the entire length of the string and sends all the keys.
